name: Quarkus native build

on: [ push ]

jobs:
  user-registrations:
    uses: klingsbo/ci-cd/.github/workflows/gradle-graalvm-build.yaml@gradle-graalvm
    with:
      java_version: '17'
      graalvm_version: '22.3.2'