name: Feature branch build

on:
  push:
    branches-ignore:
      - main

jobs:
  user-registrations-build:
    name: Build "${{ github.ref_name }}" in ${{ github.repository }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.2'
          java-version: '17'
          components: 'native-image'
          cache: 'gradle'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Gradle setup
        uses: gradle/gradle-build-action@v2

      - name: Gradle build
        run: ./gradlew build

      - name: Sonarcloud scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          args: >
            -Dsonar.organization=${{ vars.SONARCLOUD_ORGANIZATION }}
            -Dsonar.projectKey=${{ vars.SONARCLOUD_PROJECT }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONARCLOUD_TOKEN }}
