name: Feature branch build

on: [ push ]

jobs:
  user-accounts-build:
    name: Build "${{ github.ref_name }}" in ${{ github.repository }}

    runs-on: ubuntu-latest
    # Containers must run in Linux based operating systems
    # Docker Hub image that `container-job` executes in
#    container: node:10.18-jessie

    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres
        # Provide the password for postgres
        env:
          POSTGRES_DB: user-accounts
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123456

        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Check out
        uses: actions/checkout@v3

      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.2'
          java-version: '17'
          components: 'native-image'
          cache: 'gradle'
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Gradle setup
        uses: gradle/gradle-build-action@v2.4.2

      - name: Gradle build
        run: ./gradlew build
